[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "adaura_attenuator"
version = "0.1"
authors = [
  { name="supraconex", email="supraconex@supraconex.org" },
]
description = "An interface to Adaura Technologies Programmable RF Attenuators"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/supraconex.org"
"Bug Tracker" = "https://github.com/supraconex.org/issues"
